version: "3"
services:
  worker:
    build: .
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      TODOIST_TOKEN: "YOUR_TODOIST_TOKEN"
      TELEGRAM_TOKEN: "YOUR_TELEGRAM_TOKEN"
      TELEGRAM_ADMIN_ID: "YOUR_TELEGRAM_ID"
    volumes:
      - .:/usr/src/app
